---
title: "Question2"
output: html_document
---

Note: You need to be either on the campus or connected to UCD vpn in order to connect the postgres server on alan.ucdavis.edu.

```{r}
library(DBI)
chinook <- dbConnect(RPostgres::Postgres(),
  dbname = "chinook",
  user = "psqluser", password = "secret", host = "alan.ucdavis.edu"
)
```

The Chinook data model represents a digital media store, including tables for artists, albums, media tracks, invoices and customers.

- Media-related data was created using real data from an Apple iTunes library.
- Customer and employee information was created using fictitious names and addresses that can be located on Google maps, and other well formatted data (phone, fax, email, etc.)
- Sales information was auto generated using random data for a four year period.
- There are 11 tables in the chinook sample database.

  - `employees` table stores employees data such as employee id, last name, first name, etc. It also has a field named ReportsTo to specify who reports to whom.
  - `customers` table stores customers data.
  - `invoices` & `invoice_items` tables: these two tables store invoice data. The invoices table stores invoice header data and the invoice_items table stores the invoice line items data.
  - `artists` table stores artists data. It is a simple table that contains only the artist id and name.
  - `albums` table stores data about a list of tracks. Each album belongs to one artist. However, one artist may have multiple albums.
  - `media_types` table stores media types such as MPEG audio and AAC audio file.
  - `genres` table stores music types such as rock, jazz, metal, etc.
  - `tracks` table store the data of songs. Each track belongs to one album.
  - `playlists` & `playlist_track` tables: playlists table store data about playlists. Each playlist contains a list of tracks. Each track may belong to multiple playlists. The relationship between the playlists table and tracks table is many-to-many. The playlist_track table is used to reflect this relationship.
  
  See for example https://docs.yugabyte.com/images/sample-data/chinook/chinook-er-diagram.png for a database diagram.


For each of the followings, use both dplyr and sql approaches to get the answer.


(a) What is the title of the album with AlbumId 31?



(b) List all the albums by artists with the word ‘black’ in their name.



(c) Find the name and length (in seconds) of all tracks that have both length between 30 and 40 seconds, and genre Latin.



(d) Produce a table that lists each country and the number of customers in that country. (You only need to include countries that have customers.)



(e) Find the artist (or several artists) with the largest number of countries where the listeners are from.
